[package]
name = "nettfiske"
version = "0.1.0"
authors = ["Flavio Oliveira <rusty@wisespace.io>"]

[dependencies]
url = "1.6"
log = "0.4.1"
fern = "0.5.5"
chrono = "0.4.2"
tungstenite = "0.5"
publicsuffix = "1.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
console = "0.6.1"
strsim = "0.7"
lazy_static = "1.0"
idna = "0.1.4"